version: 2.1
jobs:
  check:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run:
          name: download deps
          command: npm i --dev
      - run:
          name: lint and fmt
          command: |
            npm run checkfmt
            npm run lint

  build-and-test:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run:
          name: download deps
          command: npm i --dev
      - run:
          name: build
          command: npm run compile
      - run:
          name: run tests
          command: npm test

  prerelease:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm i
      - run: npm version prerelease --no-git-tag-version
      - run: npm run prerelease

  publish:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm i
      - run: npm run publish

workflows:
  version: 2.1
  verify:
    jobs:
      - build-and-test
      - check

  prerelease:
    jobs:
      - prerelease:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/

  publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
