version: 2.1
jobs:
  check:
    docker:
      - image: circleci/node:14.16-browsers
    steps:
      - checkout
      - run:
          name: download deps
          command: npm i --dev
      - run:
          name: checkfmt
          command: npm run checkfmt
      - run:
          name: lint
          command: npm run lint
  build-and-test:
    docker:
      - image: circleci/node:14.16-browsers
    steps:
      - checkout
      - run:
          name: download deps
          command: npm i --dev
      - run:
          name: build
          command: npm run compile
      - run:
          name: run tests
          command: npm test

  publish:
    docker:
      - image: circleci/node:14.16
    steps:
      - checkout
      - run: npm i
      - run: sudo npm i -g vsce
      - run: vsce publish -p $AZURE_TOKEN

workflows:
  version: 2.1
  verify:
    jobs:
      - build-and-test
      - check

  publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
